# -*- coding: utf-8 -*-
"""ِAhmed_XGBoost_ipynb (1) (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wVzk97FiNtTFzrJpHzU0Y_8DCamX3k_3
"""

import pandas as pd

df = pd.read_csv("/content/diabetes_binary_health_indicators_BRFSS2015 (1).csv")

selected_features_final = [
    'GenHlth', 'HighBP', 'BMI', 'DiffWalk', 'HighChol',
    'Age', 'HeartDiseaseorAttack', 'PhysHlth', 'MentHlth', 'Income'
]

X = df[selected_features_final]
y = df["Diabetes_binary"]

"""Split"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='median')

X_train = imputer.fit_transform(X_train)

X_test = imputer.transform(X_test)

"""**SMOTE**"""

#SMOTE
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

#Train XGBoost
from xgboost import XGBClassifier

model = XGBClassifier(
    n_estimators=200,
    max_depth=5,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

model.fit(X_train_res, y_train_res)

"""**Evaluation**"""

from sklearn.metrics import accuracy_score, classification_report, roc_auc_score

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:,1]


print("Accuracy:", accuracy_score(y_test, y_pred))
print("AUC:", roc_auc_score(y_test, y_prob))
print(classification_report(y_test, y_pred))

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt


cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")

plt.show()

#ROC Curve
from sklearn.metrics import roc_curve

fpr, tpr, thresholds = roc_curve(y_test, y_prob)

plt.figure(figsize=(6,5))

plt.plot(fpr, tpr, label=f"AUC = {roc_auc_score(y_test, y_prob):.2f}")

plt.plot([0,1],[0,1],'--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")

plt.legend()

plt.show()

#Feature Importance
import matplotlib.pyplot as plt
import pandas as pd

importance = model.feature_importances_

pd.Series(importance, index=selected_features_final)\
    .sort_values()\
    .plot(kind='barh')

plt.title("Feature Importance")
plt.show()

"""# SHAP"""

import shap
# X_test DataFrame
X_test = pd.DataFrame(
    X_test,
    columns=selected_features_final
)

explainer = shap.Explainer(model, X_test)
shap_values = explainer(X_test)

shap.plots.bar(shap_values)

#SHAP beeswarm
explainer = shap.Explainer(model)
shap_values = explainer(X_test)

shap.plots.beeswarm(shap_values)

"""SHAP Dependence Plot"""

shap.dependence_plot(
    "BMI",
    shap_values.values,
    X_test,
    feature_names=selected_features_final
)

"""BMI Dependence Plot"""

shap.dependence_plot(
    "BMI",
    shap_values.values,
    X_test,
    feature_names=selected_features_final
)

"""# LIME"""

!pip install lime

from lime.lime_tabular import LimeTabularExplainer
import numpy as np

lime_explainer = LimeTabularExplainer(
    training_data=np.array(X_train_res),
    feature_names=selected_features_final,
    class_names=['Non-Diabetic', 'Diabetic'],
    mode='classification'
)

#Explain One Instance
exp = lime_explainer.explain_instance(
    X_test.iloc[0],
    model.predict_proba,
    num_features=10
)

fig = exp.as_pyplot_figure()
plt.tight_layout()
plt.show()

"""# ICE"""

from sklearn.inspection import PartialDependenceDisplay
import matplotlib.pyplot as plt

features_to_plot = ["BMI"]

fig, ax = plt.subplots(figsize=(8,6))

PartialDependenceDisplay.from_estimator(
    model,
    X_test,
    features=features_to_plot,
    kind="individual",
    subsample=50,
    random_state=42,
    ax=ax
)

plt.title("ICE Plot - BMI")

plt.show()